spring:
  r2dbc:
    url: ${DB_URL:r2dbc:postgresql://localhost:5432/test?currentSchema=${spring.application.name}}
    username: ${DB_LOGIN:postgres}
    password: ${DB_PASSWORD:postgres}
    pool:
      max-size: ${DATASOURCE_POOL_MAX_SIZE:10}
      min-idle: ${DATASOURCE_POOL_MIN_IDLE:1}

  liquibase:
    user: ${DB_LOGIN:postgres}
    password: ${DB_PASSWORD:postgres}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/test?currentSchema=${spring.application.name}}

management:
  endpoints:
    web:
      exposure:
        include: beans, env, health, info, metrics, mappings, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    tags:
      application: client-service

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000